[CmdletBinding()]
param(
  [string]$KeystorePath = "W:\AuditProMobile\secrets\apm-signing\apm-release.jks",
  [string]$AndroidDir = (Resolve-Path "$PSScriptRoot\..\android"),
  [string]$Alias = "apm"
)

$ErrorActionPreference = 'Stop'

function Resolve-Keytool {
  $cmd = Get-Command keytool.exe -ErrorAction SilentlyContinue | Select-Object -First 1
  if ($cmd) { return $cmd.Source }

  if ($env:JAVA_HOME) {
    $candidate = Join-Path $env:JAVA_HOME "bin\keytool.exe"
    if (Test-Path $candidate) { return $candidate }
  }

  throw "keytool.exe not found. Install a JDK and/or set JAVA_HOME."
}

$androidDirResolved = (Resolve-Path $AndroidDir).Path
$keystoreDir = Split-Path -Parent $KeystorePath

New-Item -ItemType Directory -Force -Path $keystoreDir | Out-Null

if (-not (Test-Path $KeystorePath)) {
  $keytool = Resolve-Keytool

  Write-Host "Creating keystore: $KeystorePath"
  Write-Host "You will be prompted for passwords and certificate fields."

  # Omitting -storepass / -keypass intentionally so keytool prompts interactively.
  & $keytool -genkeypair -v -keystore $KeystorePath -storetype JKS -alias $Alias -keyalg RSA -keysize 2048 -validity 10000

  if (-not (Test-Path $KeystorePath)) {
    throw "Keystore was not created at: $KeystorePath"
  }
}
else {
  Write-Host "Keystore already exists: $KeystorePath"
}

$keyPropertiesPath = Join-Path $androidDirResolved 'key.properties'
if (Test-Path $keyPropertiesPath) {
  Write-Host "key.properties already exists: $keyPropertiesPath"
  Write-Host "Edit it if needed to match your keystore passwords/alias."
  exit 0
}

Write-Host "Creating: $keyPropertiesPath"
$storePassword = Read-Host -Prompt 'Keystore storePassword (will be written to key.properties)'
$keyPassword = Read-Host -Prompt 'Keystore keyPassword (will be written to key.properties)'

# Use double backslashes for Gradle on Windows
$escapedKeystorePath = $KeystorePath.Replace('\\', '\\\\')

@"
# DO NOT COMMIT
# Generated by tools/setup_apm_android_signing.ps1

storeFile=$escapedKeystorePath
storePassword=$storePassword
keyAlias=$Alias
keyPassword=$keyPassword
"@ | Out-File -Encoding ascii -NoNewline $keyPropertiesPath

Write-Host "OK: $keyPropertiesPath"
Write-Host "Next: run tools/build_apm_android_release.ps1"
